Entity/AppUser/AppUser.php
<?php

declare(strict_types=1);

namespace OswisOrg\OswisCoreBundle\Entity\AppUser;

use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Post;
use ApiPlatform\Metadata\Put;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use OswisOrg\OswisCoreBundle\Entity\AbstractClass\AbstractAppUser;
use OswisOrg\OswisCoreBundle\Entity\NonPersistent\Export\ExportListColumn;
use OswisOrg\OswisCoreBundle\Filter\SearchFilter;
use OswisOrg\OswisCoreBundle\Interfaces\Export\PdfExportableInterface;
use OswisOrg\OswisCoreBundle\Repository\AppUserRepository;
use OswisOrg\OswisCoreBundle\Traits\Export\PdfExportableTrait;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

/**
 * @noinspection PhpUnused
 * @noinspection MethodShouldBeFinalInspection
 */

/**
 * User of application.
 * AppUser is user of this application.
 * Every **user must be activated** by activating e-mail with link that is containing special token.
 * User is **active in interval** given by *startDateTime* and *endDateTime* (no need to use *deleted* property).
 * @author Jakub Zak <mail@jakubzak.eu>
 * @OswisOrg\OswisCoreBundle\Filter\SearchAnnotation({
 *     "id",
 *     "username",
 *     "email",
 *     "givenName",
 *     "additionalName",
 *     "familyName",
 *     "nickname",
 *     "honorificPrefix",
 *     "honorificSuffix",
 *     "description",
 *     "note",
 *     "appUserType.name",
 *     "appUserType.shortName",
 *     "appUserType.slug"
 * })
 */
#[ApiResource(
    operations: [
        new GetCollection(
            normalizationContext: [
                'groups' => ["entities_get", "app_users_get"],
                'enable_max_depth' => true,
            ],
            security: "is_granted('ROLE_MANAGER')"
        ),
        new Post(
            denormalizationContext: [
                'groups' => ["entities_post", "app_users_post"],
                'enable_max_depth' => true,
            ],
            security: "is_granted('ROLE_ADMIN')"
        ),
        new Get(
            normalizationContext: [
                'groups' => ["entity_get", "app_user_get"],
                'enable_max_depth' => true,
            ],
            security: "is_granted('ROLE_MANAGER') or object.canRead(user)"
        ),
        new Put(
            denormalizationContext: [
                'groups' => ["entity_put", "app_user_put"],
                'enable_max_depth' => true,
            ],
            security: "is_granted('ROLE_ADMIN') or object.canEdit(user)"
        ),
        new Get(
            uriTemplate: '/app_users/export/pdf',
            normalizationContext: [
                'groups' => ["entities_get", "app_users_get"],
                'enable_max_depth' => true,
            ],
            security: "is_granted('ROLE_MANAGER')"
        ),
    ],
    filters: ['search'],
    security: "is_granted('ROLE_USER')"
)]
#[ApiFilter(OrderFilter::class, properties: [
    "appUserType.id",
    "appUserType.name",
    "appUserType.slug",
])]
#[ORM\Entity(repositoryClass: AppUserRepository::class)]
#[ORM\Table(name: 'core_app_user')]
#[ORM\Cache(usage: 'NONSTRICT_READ_WRITE', region: 'core_app_user')]
class AppUser extends AbstractAppUser implements PdfExportableInterface, PasswordAuthenticatedUserInterface
{
    use PdfExportableTrait;

    public const ENTITY_NAME = [1 => 'Uživatel', 11 => 'Uživatelé'];

    #[ORM\OneToMany(targetEntity: AppUserFlagConnection::class, mappedBy: 'appUser', cascade: ['all'], fetch: 'EAGER')]
    #[ApiFilter(SearchFilter::class, properties: [
        "appUserFlags.id"   => "exact",
        "appUserFlags.name" => "ipartial",
        "appUserFlags.slug" => "ipartial",
    ])]
    #[ApiFilter(OrderFilter::class, properties: ["appUserFlags.id", "appUserFlags.name", "appUserFlags.slug"])]
    protected ?Collection $appUserFlags = null;

    #[ORM\ManyToOne(targetEntity: AppUserType::class, fetch: 'EAGER')]
    #[ORM\JoinColumn(name: 'app_user_type_id', referencedColumnName: 'id')]
    #[ApiFilter(SearchFilter::class, properties: [
        "appUserType.id"   => "exact",
        "appUserType.name" => "ipartial",
        "appUserType.slug" => "ipartial",
    ])]
    protected ?AppUserType $appUserType = null;

    public function __construct(
        ?string $fullName = null,
        ?string $username = null,
        ?string $email = null,
        ?string $encryptedPassword = null,
        ?AppUserType $type = null
    ) {
        $this->appUserFlags = new ArrayCollection();
        $this->setName($fullName);
        $this->setUsername($username);
        $this->setEmail($email);
        $this->setPassword($encryptedPassword);
        $this->setAppUserType($type);
    }

    public static function getExportEntityName(int $case = 1): string
    {
        return self::ENTITY_NAME[$case];
    }

    public static function getPdfListColumns(bool $complex = false): Collection
    {
        $columns = new ArrayCollection();
        $columns->add(new ExportListColumn('id', ExportListColumn::TYPE_ID_USERNAME, 'Uživatel'));
        if (true === $complex) {
            $columns->add(new ExportListColumn('', '', '', ''));
        }

        return $columns;
    }

    /**
     * Can user visit administration?
     */
    public function isAdminUser(): bool
    {
        return (null !== $this->getAppUserType()) && ($this->getAppUserType()->getAdminUser());
    }

    public function getAppUserType(): ?AppUserType
    {
        return $this->appUserType;
    }

    public function setAppUserType(?AppUserType $appUserType): void
    {
        $this->appUserType = $appUserType;
    }

    /**
     * Can user edit this user?
     */
    public function canEdit(self $user): bool
    {
        return $this->canRead($user) && $user === $this;
    }

    /**
     * Can user read this user?
     */
    public function canRead(self $user): bool
    {
        return $user === $this;
    }

    /**
     * Returns the roles granted to the user.
     * @return array<string>|array The user roles.
     */
    public function getRoles(): array
    {
        return $this->getAppUserType()?->getAllRoleNames()->toArray() ?? [];
    }

    public function getName(): string
    {
        return (!empty($fullName = $this->getFullName()) ? $fullName : $this->getUsername()) ?? '';
    }

    public function addAppUserFlag(?AppUserFlagConnection $flagInJobFairUser): void
    {
        if ($flagInJobFairUser && !$this->getAppUserFlags()->contains($flagInJobFairUser)) {
            $this->getAppUserFlags()->add($flagInJobFairUser);
            $flagInJobFairUser->setAppUser($this);
        }
    }

    /**
     * @return Collection<AppUserFlag>
     */
    public function getAppUserFlags(): Collection
    {
        return $this->appUserFlags ?? new ArrayCollection();
    }

    public function removeAppUserFlag(?AppUserFlagConnection $flagInEmployer): void
    {
        if ($flagInEmployer && $this->getAppUserFlags()->removeElement($flagInEmployer)) {
            $flagInEmployer->setAppUser(null);
        }
    }

    /**
     * @param string|null                 $plainPassword
     * @param UserPasswordHasherInterface $encoder
     */
    public function encryptPassword(?string $plainPassword, UserPasswordHasherInterface $encoder): void
    {
        $this->setPassword($encoder->hashPassword($this, ''.$plainPassword));
    }

    /**
     * @return non-empty-string
     */
    public function getUserIdentifier(): string
    {
        return !empty($this->getUsername()) ? $this->getUsername() : $this->getEmail();
    }
}

Entity/AppUser/AppUserRole.php
<?php

/**
 * @noinspection PhpUnused
 * @noinspection PropertyCanBePrivateInspection
 * @noinspection MethodShouldBeFinalInspection
 */
declare(strict_types=1);

namespace OswisOrg\OswisCoreBundle\Entity\AppUser;

use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping\Cache;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\JoinColumn;
use Doctrine\ORM\Mapping\ManyToOne;
use Doctrine\ORM\Mapping\Table;
use InvalidArgumentException;
use OswisOrg\OswisCoreBundle\Entity\NonPersistent\Nameable;
use OswisOrg\OswisCoreBundle\Filter\SearchAnnotation as Searchable;
use OswisOrg\OswisCoreBundle\Filter\SearchFilter;
use OswisOrg\OswisCoreBundle\Interfaces\Common\NameableInterface;
use OswisOrg\OswisCoreBundle\Repository\AppUserRoleRepository;
use OswisOrg\OswisCoreBundle\Traits\Common\NameableTrait;

/**
 * Role of app user.
 * @author Jakub Zak <mail@jakubzak.eu>
 * @Searchable({
 *     "id",
 *     "slug",
 *     "forcedSlug",
 *     "name",
 *     "shortName",
 *     "description",
 *     "note",
 *     "roleString"
 * })
 * @ApiResource(
 *   attributes={
 *     "filters"={"search"},
 *     "security"="is_granted('ROLE_ADMIN')",
 *     "normalization_context"={"groups"={"app_user_roles_get"}, "enable_max_depth"=true},
 *     "denormalization_context"={"groups"={"app_user_roles_post"}, "enable_max_depth"=true}
 *   },
 *   collectionOperations={
 *     "get"={
 *       "security"="is_granted('ROLE_ADMIN')",
 *       "normalization_context"={"groups"={"app_user_roles_get"}, "enable_max_depth"=true},
 *     },
 *     "post"={
 *       "security"="is_granted('ROLE_ROOT')",
 *       "denormalization_context"={"groups"={"app_user_roles_post"}, "enable_max_depth"=true}
 *     }
 *   },
 *   itemOperations={
 *     "get"={
 *       "security"="is_granted('ROLE_ADMIN')",
 *       "normalization_context"={"groups"={"app_user_role_get"}, "enable_max_depth"=true},
 *     },
 *     "put"={
 *       "security"="is_granted('ROLE_ROOT')",
 *       "denormalization_context"={"groups"={"app_user_role_put"}, "enable_max_depth"=true}
 *     }
 *   }
 * )
 */
#[Entity(repositoryClass: AppUserRoleRepository::class)]
#[Table(name: 'core_app_user_role')]
#[Cache(usage: 'NONSTRICT_READ_WRITE', region: 'core_app_user')]
class AppUserRole implements NameableInterface
{
    use NameableTrait;

    public const ROLE_EVERYBODY = 'ROLE_EVERYBODY';
    public const ROLE_CUSTOMER  = 'ROLE_CUSTOMER';
    public const ROLE_USER      = 'ROLE_USER';
    public const ROLE_MEMBER    = 'ROLE_MEMBER';
    public const ROLE_MANAGER   = 'ROLE_MANAGER';
    public const ROLE_ADMIN     = 'ROLE_ADMIN';
    public const ROLE_ROOT      = 'ROLE_ROOT';
    public const ROLES_PARENT
                                = [
            self::ROLE_CUSTOMER => self::ROLE_EVERYBODY,
            self::ROLE_USER     => self::ROLE_CUSTOMER,
            self::ROLE_MEMBER   => self::ROLE_USER,
            self::ROLE_MANAGER  => self::ROLE_MEMBER,
            self::ROLE_ADMIN    => self::ROLE_MANAGER,
            self::ROLE_ROOT     => self::ROLE_ADMIN,
        ];

    #[ApiFilter(SearchFilter::class, strategy: 'ipartial')]
    #[ApiFilter(OrderFilter::class)]
    #[Column(type: 'string', nullable: true)]
    protected ?string $roleString = null;

    #[ManyToOne(targetEntity: self::class, fetch: 'EAGER')]
    #[JoinColumn(name: 'parent_id', referencedColumnName: 'id')]
    #[ApiFilter(SearchFilter::class, properties: [
        "parent.id"   => "exact",
        "parent.name" => "ipartial",
        "parent.slug" => "ipartial",
    ])]
    #[ApiFilter(OrderFilter::class)]
    protected ?self $parent = null;

    /**
     * AppUserRole constructor.
     *
     * @param  Nameable|null  $nameable
     * @param  string|null  $roleString
     * @param  \OswisOrg\OswisCoreBundle\Entity\AppUser\AppUserRole|null  $parent
     *
     * @throws InvalidArgumentException
     */
    public function __construct(?Nameable $nameable = null, ?string $roleString = null, ?self $parent = null)
    {
        $this->parent = null;
        $this->roleString = $roleString;
        $this->setFieldsFromNameable($nameable);
        $this->setParent($parent);
    }

    /** Get names of all contained roles. */
    public function getAllRoleNames(): Collection
    {
        return $this->getRoles()->map(fn(mixed $role) => $role instanceof self ? $role->getRoleName() : null);
    }

    /**
     * Get all contained roles.
     * @return Collection<self>
     */
    public function getRoles(): Collection
    {
        /** @var Collection<self> $roles */
        $roles = new ArrayCollection([$this]);
        foreach ($this->getParent()?->getRoles() ?? new ArrayCollection() as $role) {
            if (!$roles->contains($role)) {
                $roles->add($role);
            }
        }

        return $roles;
    }

    public function getParent(): ?self
    {
        return $this->parent;
    }

    /**
     * @param  self|null  $appUserRole
     *
     * @throws InvalidArgumentException
     */
    public function setParent(?self $appUserRole): void
    {
        if ($this === $appUserRole) {
            throw new InvalidArgumentException('Role nemůže být nadřazenou sama sobě.');
        }
        $this->parent = $appUserRole;
    }

    /**
     * Get name/string of role.
     * @example ROLE_USER
     */
    public function getRoleName(): string
    {
        return empty($this->getRoleString()) ? '' : 'ROLE_'.$this->getRoleString();
    }

    public function getRoleString(): string
    {
        return $this->roleString ?? '';
    }

    public function setRoleString(string $roleString): void
    {
        $this->roleString = $roleString;
    }
}

Controller/WebAdmin/WebAdminController.php
<?php

declare(strict_types=1);

namespace OswisOrg\OswisCoreBundle\Controller\WebAdmin;

use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Routing\Attribute\Route;

class WebAdminController extends AbstractController
{
    /**
     * @return Response
     */
    #[Route(path: '/web_admin/homepage', name: 'web_admin_homepage')]
    final public function showAdminHomepage(): Response
    {
        return $this->render('@OswisOrgOswisCore/web_admin/web-admin-homepage.html.twig');
    }

    final public function testSession(Session $session): Response
    {
        $date = new DateTime();
        $timestamp = $date->getTimestamp();
        $session->set(''.$timestamp, $date->format("d.m.Y H:i:s"));

        return $this->render('@OswisOrgOswisCore/web_admin/sessions.html.twig');
    }
}

Controller/WebAdmin/WebSecurityController.php
<?php

/**
 * @noinspection MethodShouldBeFinalInspection
 */
declare(strict_types=1);

namespace OswisOrg\OswisCoreBundle\Controller\WebAdmin;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class WebSecurityController extends AbstractController
{
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        return $this->render('@OswisOrgOswisCore/web_admin/login.html.twig', [
            'last_username' => $authenticationUtils->getLastUsername(),
            'error'         => $authenticationUtils->getLastAuthenticationError(),
        ]);
    }

    public function logout(): void
    {
        // Dummy method for logout action.
    }
}

Resources/views/web_admin/header.html.twig
{% extends '@!OswisOrgOswisCore/web/parts/header.html.twig' %}

{% block header_container %}
    <div class="container" id="main-header-container">
        <div class="row no-gutter header-row" id="main-header-row">
            <div id="main-header-main-menu" class="col-12 d-print-none">
                {% block main_menu %}
                    {{ render_esi(controller('OswisOrg\\OswisCoreBundle\\Controller\\Web\\WebMenuController::showMenu', {'menu': 'web-admin-menu'})) }}
                {% endblock main_menu %}
            </div>
        </div>
    </div>
{% endblock header_container %}

Resources/views/web_admin/html-skeleton-web-admin.html.twig
{% extends '@OswisOrgOswisCore/web/html-skeleton-default.html.twig' %}

Resources/views/web_admin/login.html.twig
{% extends '@OswisOrgOswisCore/web/page-skeleton-default.html.twig' %}

{% block html_title %}Přihlášení{% endblock %}

{% block body_content %}
    <main class="container" id="main-content-container">
        <div class="row">
            {% if error %}
                <div class="col-12">
                    <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
                </div>
            {% endif %}
            {% if app.user %}
                <div class="col-12">
                    <div class="m-3">
                        Přihlášen(a) jako <strong>{{ app.user.userIdentifier }}</strong>.
                    </div>
                    <table class="list">
                        <tbody>
                        <tr>
                            <td>Jméno:</td>
                            <td>{{ app.user.name }}</td>
                        </tr>
                        </tbody>
                        <tbody>
                        <tr>
                            <td>Uživatelské jméno:</td>
                            <td>{{ app.user.userIdentifier }}</td>
                        </tr>
                        </tbody>
                        <tbody>
                        <tr>
                            <td>E-mail:</td>
                            <td>{{ app.user.email }}</td>
                        </tr>
                        </tbody>
                        <tbody>
                        <tr>
                            <td>Typ uživatele:</td>
                            <td>{{ app.user.appUserType.name }}</td>
                        </tr>
                        </tbody>
                        <tbody>
                        <tr>
                            <td>Role uživatele:</td>
                            <td>{{ app.user.appUserType.allRoleNames|join(', ') }}</td>
                        </tr>
                        </tbody>
                    </table>
                    <div class="m-3">
                        <strong>Pokračovat:</strong>
                        <ul>
                            <li><a href="{{ path('oswis_org_oswis_core_homepage_action') }}">na&nbsp;web</a></li>
                            {% if app.user.role('ROLE_MANAGER') or app.user.role('ROLE_ADMIN') %}
                                <li>
                                    <a href="{{ path('oswis_org_oswis_core_web_admin_homepage') }}">do&nbsp;administrace</a>
                                </li>
                            {% endif %}
                            <li><a href="{{ path('oswis_org_oswis_core_portal') }}">do&nbsp;aplikace</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-12">
                    <form action="{{ path('oswis_org_oswis_core_web_admin_logout') }}">
                        <button class="btn btn-lg btn-primary m-3" type="submit">
                            Odhlásit
                        </button>
                    </form>
                </div>
            {% endif %}
            {% if not app.user %}
                <form method="post">
                    <div class="col-12">
                        <h1 class="h3 mb-3 font-weight-normal">Přihlášení</h1>
                        <label for="inputUsername">
                            <span>Uživatelské jméno nebo e-mail:<br></span>
                            <input type="text" value="{{ last_username }}" name="_username" id="inputUsername"
                                   class="form-control" required autofocus>
                        </label>
                    </div>
                    <div class="col-12">
                        <label for="inputPassword">
                            <span>Heslo:<br></span>
                            <input type="password" name="_password" id="inputPassword" class="form-control" required>
                        </label>
                    </div>
                    <div class="col-12">
                        <div class="checkbox mb-3">
                            <label><input type="checkbox" name="_remember_me">&nbsp;Zapamatovat</label>
                        </div>
                    </div>
                    <div class="col-12">
                        <button class="btn btn-lg btn-primary m-3" type="submit">
                            Přihlásit
                        </button>
                    </div>
                </form>
            {% endif %}
        </div>
    </main>
{% endblock %}

Resources/views/web_admin/page-skeleton-web-admin.html.twig
{% extends '@OswisOrgOswisCore/web/page-skeleton-default.html.twig' %}

{% block body_header %}
    {% include '@OswisOrgOswisCore/web_admin/header.html.twig' %}
{% endblock body_header %}

Resources/views/web_admin/sessions.html.twig
<html lang="en">
<head>
    <title>Session test</title>
    <style>
        table td {
            border: 1px solid grey;
            text-align: center;
        }
    </style>
</head>
<body>
<div>
    <h1>SESSIONS</h1>
    <table style="min-width: 500px; margin: auto;">
        {% for key, session in app.session.all %}
            <tr>
                <td>{{ key }}</td>
                <td>{{ session }}</td>
            </tr>
        {% endfor %}
    </table>
</div>
</body>
</html>

Resources/views/web_admin/web-admin-homepage.html.twig
{% extends '@OswisOrgOswisCore/web_admin/page-skeleton-web-admin.html.twig' %}

{% block html_title %}Úvod :: ADMIN{% endblock %}

{% block body_content %}
    <main class="container" id="main-content-container">
        <div class="row">
            <div class="col">
                <table class="list">
                    <tbody>
                    <tr>
                        <td>Jméno:</td>
                        <td>{{ app.user.name }}</td>
                    </tr>
                    </tbody>
                    <tbody>
                    <tr>
                        <td>Uživatelské jméno:</td>
                        <td>{{ app.user.userIdentifier }}</td>
                    </tr>
                    </tbody>
                    <tbody>
                    <tr>
                        <td>E-mail:</td>
                        <td>{{ app.user.email }}</td>
                    </tr>
                    </tbody>
                    <tbody>
                    <tr>
                        <td>Typ uživatele:</td>
                        <td>{{ app.user.appUserType.name }}</td>
                    </tr>
                    </tbody>
                    <tbody>
                    <tr>
                        <td>Role uživatele:</td>
                        <td>{{ app.user.appUserType.allRoleNames|join(', ') }}</td>
                    </tr>
                    </tbody>
                </table>

                <div class="m-3">
                    <strong>Pokračovat:</strong>
                    <ul>
                        <li><a href="{{ path('oswis_org_oswis_core_homepage_action') }}">na&nbsp;web</a></li>
                        <li><a href="{{ path('oswis_org_oswis_core_portal') }}">do&nbsp;aplikace</a></li>
                    </ul>
                </div>

            </div>
        </div>


        <div class="row">
            <div class="col">

                {% if app.user.role('ROLE_MANAGER') or app.user.role('ROLE_ADMIN') %}
                    <h2>Systémové akce</h2>
                    <ul>
                        <li>
                            <a href="{{ path('oswis_org_oswis_core_internal_action_clear_cache') }}">Smazat cache</a>
                        </li>
                        <li>
                            <a href="{{ path('oswis_org_oswis_core_web_admin_test_session') }}">Test session</a>
                        </li>
                    </ul>
                {% endif %}

                {% block additional_actions %}
                {% endblock %}


            </div>
        </div>


    </main>
{% endblock %}